version: '3.9'

services:
  node_server:
    build:
      context: ./node-server
    restart: always
    environment:
      PORT: 9090
      APP_INSIGHTS_KEY: "$APP_INSIGHTS_KEY"
  node_client:
    build:
      context: ./node-client
    restart: always
    ports:
      - "6060:6060"
    environment:
      PORT: 6060
      SERVER_URL: http://node_server:9090
      APP_INSIGHTS_KEY: "$APP_INSIGHTS_KEY"
    depends_on:
      - node_server
  java_client:
    build:
      context: ./java-client
    restart: always
    ports:
      - "7070:7070"
    environment:
      SERVER_PORT: 7070
      SERVER_URL: http://node_server:9090
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$APP_INSIGHTS_KEY;IngestionEndpoint=https://westeurope-2.in.applicationinsights.azure.com/"
    depends_on:
      - node_server
